pages:
  type: deploy
  stage: deploy
  image: joajfreitas/arch-python
  before_script:
    - pacman -Syu --noconfirm
    - yes | pip3 install markdown || true
    - yes | pip3 install click || true
    - yes | pip3 install loguru || true
    - yes | pip3 install literate-vim || true
  script:
    - mkdir public
    - make -C nvim/.config/nvim
    - cp -r nvim/.config/nvim/html public
  artifacts:
    paths:
    - public
    expire_in: 1 week
