pages:
  type: deploy
  stage: deploy
  image: joajfreitas/arch-python
  before_script:
    - pacman -Syu --noconfirm
    - yes | pip3 install markdown || true
    - yes | pip3 install click || true
    - yes | pip3 install loguru || true
  script:
    - mkdir public
    - ./nvim/.config/nvim/lit.py web ./nvim/.config/nvim/src public
    - cp nvim/.config/nvim/public/*.css public
  artifacts:
    paths:
    - public
    expire_in: 1 week
